### ISSUE TITLE
Add Tags and Categories link next to Home and Archives hyperlinks at right top

### ISSUE THREAD

**Issue by ApoTheOne** [ApoTheOne/apotheone.github.io#9]
Tags and Categories implementation is pending, commented at
https://github.com/ApoTheOne/apotheone.github.io/blob/bad5bc8bc43079f9f45662dbc8c7d932983a3500/themes/clean-blog/_config.yml#L5

**Comment by Djanilson** [comment]
I want work on this but let me understand your problem, is it just to create an option in the menu called "tags and categories" ok?

**Comment by ApoTheOne** [comment]
Hi @Djanilson , this would involve 
- [ ] un-commenting two lines :
https://github.com/ApoTheOne/apotheone.github.io/blob/7beb9d2a3fba9ecdfdaa8f0fa86d3d408627b95c/themes/clean-blog/_config.yml#L5
- [ ] And then by adding a page.
Please go through the [documentation](https://github.com/klugjo/hexo-theme-clean-blog#tags-page) for adding tags and categories.
Let me know if you wish to go ahead or need help.
Cheers!

**Comment by ApoTheOne** [comment]
@Djanilson Thanks a lot for the contribution. Great job!
Please feel free to add your learning or notes.
